name: CI Frontend Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

env:
  Frontend_dir: /home/runner/work/TaskCrew/TaskCrew/frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Navigate to frontend directory
        run: cd ${{ env.Frontend_dir }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd ${{ env.Frontend_dir }}
          npm install

      - name: Run Prettier
        run: |
          cd ${{ env.Frontend_dir }}
          npm run format

      - name: Run tests
        run: |
          cd ${{ env.Frontend_dir }}
          npm test

      - name: Build the project
        run: |
          cd ${{ env.Frontend_dir }}
          npm run build
