name: CI User Service Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

env:
  UserService_dir: /home/runner/work/TaskCrew/TaskCrew/services/user-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Navigate to User Service directory
        run: cd ${{ env.UserService_dir }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd ${{ env.UserService_dir }}
          npm install

      - name: Run ESLint
        run: |
          cd ${{ env.UserService_dir }}
          npm run lint

      - name: Run Prettier
        run: |
          cd ${{ env.UserService_dir }}
          npm run format

      # - name: Run tests
      #   run: |
      #     cd ${{ env.UserService_dir }}
      #     npm test -- --passWithNoTests

      - name: Build the project
        run: |
          cd ${{ env.UserService_dir }}
          npm run build
